$pdf_mode = 3;
$engine = 'uplatex';
$latex = 'uplatex %O %S -kanji=utf8 -synctex=1 -interaction=nonstopmode';
$bibtex = 'upbibtex';
$dvipdf = 'dvipdfmx %O -o %D %S';
$makeindex = 'mendex %O -o %D %S';